let petNames = ['Darcy ', 'Jack ', 'Jerry ', 'Marty ', 'Vito ', 'Vinny ', 'Riley ', 'Saddie ', 'Marge ', 'Sam ']
petNames.splice(5,1)
alert(petNames)
petNames.splice(3,1)
alert(petNames)
petNames.unshift('Nancy')
alert(petNames)
petNames.push('Ryan')
alert(petNames)
alert(petNames.indexOf("Riley "))
alert(petNames.indexOf('cindy'))
let withMarmaduke = [petNames + ' Marmaduke']
alert(withMarmaduke)
let x = petNames.shift() 
alert(x)
petNames.unshift('Barney ')
alert(petNames)
let allPets= petNames.concat([', Ted ', 'Fred ' , 'Jed ', 'Ned ', 'Ed ', 'Zed '])
alert(allPets)
let y = allPets.shift()
alert(y)
let pets = allPets.join()
alert(pets)
allPets.unshift('Aguns')
alert(allPets)